### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by sleeptil3** [sleeptil3/mercury-marathon-react#4]
- [ ] An introduction of your app along with a screenshot (one is all you need to "introduce" your application).
- [ ] Explanations of the technologies used (including outside APIs).
- [ ] Explanation of different endpoints
- [ ] File structure?
- [ ] A link to your pitch-deck.
- [ ] A link to your Trello board that contains your user stories, ERD, and wireframes.
- [ ] A link to your deployed app on Heroku.
- [ ] Description of any future enhancements planned

Technologies
- [ ] Django REST ?
- [ ] Junction tables (many-to-many relationship)
- [ ] Material-ui ?
- [ ] Mockaroo ([example](https://my.api.mockaroo.com/results/123?key=d6efe6b0)) for initial development

**Comment by shamseen** [comment]
> A link to your Trello board that contains your user stories, ERD, and wireframes.

i think we can put the ERD, wireframes, app architecture diagram in a separate markdown instead, right?
